In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline
import re
import cpi

import plotly.offline
import plotly.graph_objs as go
plotly.offline.init_notebook_mode(connected = True)

In [2]:
# source of the data https://www.kaggle.com/c/tmdb-box-office-prediction/data

train_df = pd.read_csv('./data/train.csv')
test_df = pd.read_csv('./data/test.csv')

# train_df.head()

In [3]:
cols = ['original_title', 'title', 'belongs_to_collection', 'genres', 'homepage', 'original_language', 'production_companies', 'runtime', 'release_date', 'budget', 'revenue']
df = train_df[cols]
df.head()

,original_title,title,belongs_to_collection,genres,homepage,original_language,production_companies,runtime,release_date,budget,revenue
0,Hot Tub Time Machine 2,Hot Tub Time Machine 2,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...","[{'id': 35, 'name': 'Comedy'}]",NaN,en,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",93.0,2/20/15,14000000,12314651
1,The Princess Diaries 2: Royal Engagement,The Princess Diaries 2: Royal Engagement,"[{'id': 107674, 'name': 'The Princess Diaries ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,en,"[{'name': 'Walt Disney Pictures', 'id': 2}]",113.0,8/6/04,40000000,95149435
2,Whiplash,Whiplash,NaN,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...",105.0,10/10/14,3300000,13092000
3,Kahaani,Kahaani,NaN,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,NaN,122.0,3/9/12,1200000,16000000
4,마린보이,Marine Boy,NaN,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,ko,NaN,118.0,2/5/09,0,3923970

In [4]:
def col_string_extraction(col_name):

    col_name_list = []

    for i in range(df.shape[0]):
        st = df[col_name].iloc[i]
        # some movies have production compnaies as null
        if type(st) != str:
            col_name_list.append(['NaN'])
        
        else:
            subs = re.findall("\{(.*?)\}", str(st))

            col = []
            for j in range(len(subs)):
                extracted = re.findall("\: '(.*?)\'", subs[j])
                # some entries do not fit in the regex above
                if len(extracted) != 0:
                    col.append(extracted[0])
                else:
                    continue

            col_name_list.append(col)
    
    return col_name_list

In [5]:
production_company_list = col_string_extraction('production_companies')
genre_list = col_string_extraction('genres')
collection_list = col_string_extraction('belongs_to_collection')
flat_collection_list = [i for sub in collection_list for i in sub]

df.insert(2, 'genre', genre_list)
df.insert(3, 'collection', flat_collection_list)
df.insert(4, 'production_company', production_company_list)

df = df.drop(['genres', 'production_companies', 'belongs_to_collection'], axis = 1)
df.head()

,original_title,title,genre,collection,production_company,homepage,original_language,runtime,release_date,budget,revenue
0,Hot Tub Time Machine 2,Hot Tub Time Machine 2,[Comedy],Hot Tub Time Machine Collection,"[Paramount Pictures, United Artists, Metro-Gol...",NaN,en,93.0,2/20/15,14000000,12314651
1,The Princess Diaries 2: Royal Engagement,The Princess Diaries 2: Royal Engagement,"[Comedy, Drama, Family, Romance]",The Princess Diaries Collection,[Walt Disney Pictures],NaN,en,113.0,8/6/04,40000000,95149435
2,Whiplash,Whiplash,[Drama],NaN,"[Bold Films, Blumhouse Productions, Right of W...",http://sonyclassics.com/whiplash/,en,105.0,10/10/14,3300000,13092000
3,Kahaani,Kahaani,"[Thriller, Drama]",NaN,[NaN],http://kahaanithefilm.com/,hi,122.0,3/9/12,1200000,16000000
4,마린보이,Marine Boy,"[Action, Thriller]",NaN,[NaN],NaN,ko,118.0,2/5/09,0,3923970

In [6]:
# extract release year and store in the following format xxxx

release_year = df['release_date'].apply(lambda x: x.split('/')[-1])

release_year_adj = []

for i in range(len(release_year)):
    if 0 <= int(release_year[i]) <= 20:
        year = str(20) + str(release_year[i])
        release_year_adj.append(year)
    else:
        year = str(19) + str(release_year[i])
        release_year_adj.append(year)
        
df.insert(8, 'release_year', release_year_adj)

# adjustment for revenue 
adjusted_revenue = []
for i in range(df.shape[0]):
    value = cpi.inflate(df['revenue'].iloc[i], int(df['release_year'].iloc[i]), to = 2018)
    adjusted_revenue.append(int(value))
    
df.insert(10, 'adjusted_revenue', adjusted_revenue)

sequals - revenue, release_date
language - revenue
production company - revenue, date

### Disney

In [7]:
# movies produced by walt disney 

disney_movies = []

for i in range(df.shape[0]):
    if 'Walt Disney Pictures' in df['production_company'].iloc[i]:
        name = df['original_title'].iloc[i]
        disney_movies.append(name)

In [8]:
disney_df = df[df['original_title'].isin(disney_movies)]
disney_df

,original_title,title,genre,collection,production_company,homepage,original_language,runtime,release_year,release_date,adjusted_revenue,budget,revenue
1,The Princess Diaries 2: Royal Engagement,The Princess Diaries 2: Royal Engagement,"[Comedy, Drama, Family, Romance]",The Princess Diaries Collection,[Walt Disney Pictures],NaN,en,113.0,2004,8/6/04,126483267,40000000,95149435
8,Muppet Treasure Island,Muppet Treasure Island,"[Action, Comedy, Music, Family, Adventure]",The Muppet Collection,"[Walt Disney Pictures, Jim Henson Productions,...",NaN,en,100.0,1996,2/16/96,54938484,0,34327391
121,Tarzan,Tarzan,"[Adventure, Animation, Drama, Family]",Tarzan (Animation) Collection,[Walt Disney Pictures],http://disneydvd.disney.go.com/tarzanr-special...,en,88.0,1999,6/18/99,675245714,150000000,448000000
155,Return to Never Land,Return to Never Land,"[Adventure, Fantasy, Animation, Family]",Peter Pan Collection,"[Walt Disney Pictures, Walt Disney Television ...",NaN,en,72.0,2002,2/14/02,153347907,20000000,109862682
188,WALL·E,WALL·E,"[Animation, Family]",NaN,"[Walt Disney Pictures, Pixar Animation Studios...",http://disney.go.com/disneypictures/wall-e/,en,98.0,2008,6/22/08,608003870,180000000,521311860
309,Freaky Friday,Freaky Friday,[Comedy],NaN,"[Walt Disney Pictures, Gunn Films, Casual Frid...",NaN,en,97.0,2003,8/3/03,150432652,26000000,110230332
314,Cars 3,Cars 3,"[Family, Comedy, Animation, Adventure]",Cars Collection,"[Walt Disney Pictures, Pixar Animation Studios]",http://cars.disney.com,en,109.0,2017,6/15/17,358722880,175000000,350170057
335,Million Dollar Arm,Million Dollar Arm,[Drama],NaN,[Walt Disney Pictures],http://movies.disney.com/million-dollar-arm,en,124.0,2014,5/9/14,40633081,25000000,38307627
357,The Lion King,The Lion King,"[Family, Animation, Drama]",The Lion King Collection,"[Walt Disney Pictures, Walt Disney Feature Ani...",http://movies.disney.com/the-lion-king,en,89.0,1994,6/23/94,1335580483,45000000,788241776
461,The Game Plan,The Game Plan,"[Comedy, Family]",NaN,"[Walt Disney Pictures, Mayhem Pictures, Monkey...",http://movies.disney.com/the-game-plan,en,110.0,2007,9/28/07,179094633,22000000,147880543
585,दंगल,Dangal,[Drama],NaN,"[Walt Disney Pictures, Aamir Khan Productions]",NaN,hi,161.0,2016,12/23/16,324337081,10400000,310000000
684,Beauty and the Beast,Beauty and the Beast,"[Family, Fantasy, Romance]",NaN,"[Walt Disney Pictures, Mandeville Films]",http://movies.disney.com/beauty-and-the-beast-...,en,129.0,2017,3/16/17,1293732047,160000000,1262886337
712,Eight Below,Eight Below,"[Adventure, Drama, Family]",NaN,"[Walt Disney Pictures, Spyglass Entertainment,...",NaN,en,120.0,2006,2/17/06,150036425,40000000,120455994
734,Zootopia,Zootopia,"[Animation, Adventure, Family, Comedy]",NaN,"[Walt Disney Pictures, Walt Disney Animation S...",http://movies.disney.com/zootopia,en,108.0,2016,2/11/16,1071132833,150000000,1023784195
735,Honey I Blew Up the Kid,Honey I Blew Up the Kid,"[Adventure, Comedy, Family, Science Fiction]","Honey, I Shrunk the Kids Collection","[Walt Disney Pictures, Touchwood Pacific Partn...",NaN,en,89.0,1992,7/16/92,104993245,40000000,58662452
791,The Little Mermaid,The Little Mermaid,"[Animation, Family]",The Little Mermaid Collection,"[Walt Disney Pictures, Silver Screen Partners IV]",NaN,en,83.0,1989,11/17/89,450170049,40000000,222300000
804,The Jungle Book 2,The Jungle Book 2,"[Family, Animation, Adventure]",The Jungle Book Collection,"[Walt Disney Pictures, Walt Disney Television ...",NaN,en,72.0,2003,2/7/03,185164118,20000000,135680000
824,Home on the Range,Home on the Range,"[Animation, Family]",NaN,[Walt Disney Pictures],http://movies.disney.com/home-on-the-range,en,76.0,2004,4/2/04,138183904,110000000,103951461
881,Alice in Wonderland,Alice in Wonderland,"[Family, Fantasy, Adventure]",Alice in Wonderland Collection,"[Walt Disney Pictures, Team Todd, Tim Burton P...",http://disney.go.com/wonderland/,en,108.0,2010,3/3/10,1180925983,200000000,1025491110
922,A Goofy Movie,A Goofy Movie,"[Romance, Animation, Family, Comedy, Adventure]",A Goofy Movie Collection,[Walt Disney Pictures],NaN,en,78.0,1995,4/7/95,58243308,0,35348597
941,Maleficent,Maleficent,"[Fantasy, Adventure, Action, Family, Romance]",NaN,"[Walt Disney Pictures, Walt Disney Studios Mot...",http://movies.disney.com/maleficent,en,97.0,2014,5/28/14,804586753,180000000,758539785
974,Tron,Tron,"[Science Fiction, Action, Adventure]",TRON Collection,"[Walt Disney Pictures, Lisberger/Kushner]",NaN,en,96.0,1982,7/9/82,85870787,17000000,33000000
1041,The Pacifier,The Pacifier,"[Action, Comedy, Drama, Family, Thriller]",NaN,"[Walt Disney Pictures, Spyglass Entertainment]",http://movies.disney.com/the-pacifier,en,95.0,2005,3/4/05,145298610,56000000,113006880
1042,National Treasure,National Treasure,"[Adventure, Action, Thriller, Mystery]",National Treasure Collection,"[Walt Disney Pictures, Jerry Bruckheimer Films...",NaN,en,131.0,2004,11/19/04,461871904,100000000,347451894
1145,The Santa Clause 3: The Escape Clause,The Santa Clause 3: The Escape Clause,"[Comedy, Family, Adventure]",The Santa Clause Collection,"[Walt Disney Pictures, Boxing Cat Films, Outla...",NaN,en,98.0,2006,11/1/06,105250853,12000000,84500122
1164,The Three Musketeers,The Three Musketeers,"[Action, Adventure, Comedy]",NaN,"[Walt Disney Pictures, Caravan Pictures]",http://movies.disney.com/the-three-musketeers,en,105.0,1993,11/11/93,93663510,30000000,53898845
1222,Cars 2,Cars 2,"[Animation, Family, Adventure, Comedy]",Cars Collection,"[Walt Disney Pictures, Pixar Animation Studios]",http://www.disney.go.com/cars/,en,106.0,2011,6/11/11,624982131,200000000,559852396
1229,The Sorcerer's Apprentice,The Sorcerer's Apprentice,"[Fantasy, Adventure, Action, Comedy, Drama]",NaN,"[Walt Disney Pictures, Jerry Bruckheimer Films...",http://disney.go.com/disneypictures/sorcerersa...,en,109.0,2010,7/13/10,247914547,150000000,215283742
1270,John Carter,John Carter,"[Action, Adventure, Science Fiction]",NaN,[Walt Disney Pictures],http://movies.disney.com/john-carter,en,132.0,2012,3/7/12,310762985,260000000,284139100
1323,Squanto: A Warrior's Tale,Squanto: A Warrior's Tale,"[Drama, Family]",NaN,[Walt Disney Pictures],NaN,en,102.0,1994,10/28/94,5655304,0,3337685
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,The Haunted Mansion,The Haunted Mansion,"[Thriller, Fantasy, Comedy, Family, Mystery]",NaN,"[Walt Disney Pictures, Gunn Films, Doom Buggy ...",NaN,en,87.0,2003,11/25/03,248773705,90000000,182290266
1554,Hercules,Hercules,"[Action, Adventure, Fantasy]",Hercules (Lou Ferrigno) Collection,"[Cannon Group, Metro-Goldwyn-Mayer (MGM), Gola...",NaN,en,98.0,1983,8/12/83,26916335,0,10676194
1624,Hercules,Hercules,"[Animation, Family, Fantasy, Adventure, Comedy...",NaN,[Walt Disney Pictures],NaN,en,93.0,1997,6/26/97,395375561,85000000,252712101
1856,TRON: Legacy,TRON: Legacy,"[Adventure, Action, Science Fiction]",TRON Collection,"[Walt Disney Pictures, LivePlanet, Prana Studi...",http://disney.go.com/tron/,en,125.0,2010,12/10/10,460700738,170000000,400062763
1862,Herbie Fully Loaded,Herbie Fully Loaded,"[Comedy, Family, Adventure, Fantasy, Romance]",Herbie Collection,"[Walt Disney Pictures, Robert Simonds Producti...",NaN,en,101.0,2005,6/22/05,84862085,50000000,66002004
1932,The Odd Life of Timothy Green,The Odd Life of Timothy Green,"[Fantasy, Drama, Comedy, Family]",NaN,[Walt Disney Pictures],http://disney.go.com/disneypictures/the-odd-li...,en,105.0,2012,8/15/12,56713686,0,51854875
1962,Glory Road,Glory Road,[Drama],NaN,[Walt Disney Pictures],NaN,en,118.0,2006,1/13/06,53120401,0,42647449
1976,The Finest Hours,The Finest Hours,"[Action, Drama, History, Thriller]",NaN,"[Walt Disney Pictures, Whitaker Entertainment,...",https://www.facebook.com/thefinesthoursmovie,en,114.0,2016,1/25/16,54508602,80000000,52099090
2047,Prom,Prom,[Comedy],NaN,"[Walt Disney Pictures, Rickshaw Productions]",http://disney.go.com/disneypictures/prom/index...,en,104.0,2011,4/29/11,11308461,8000000,10130000
2097,Pirates of the Caribbean: The Curse of the Bla...,Pirates of the Caribbean: The Curse of the Bla...,"[Adventure, Fantasy, Action]",Pirates of the Caribbean Collection,"[Walt Disney Pictures, Jerry Bruckheimer Films]",http://disney.go.com/disneyvideos/liveaction/p...,en,143.0,2003,7/9/03,893901649,140000000,655011224
2126,Guardians of the Galaxy Vol. 2,Guardians of the Galaxy Vol. 2,"[Action, Adventure, Comedy, Science Fiction]",Guardians of the Galaxy Collection,"[Walt Disney Pictures, Marvel Studios]",http://marvel.com/movies/movie/221/guardians_o...,en,137.0,2017,4/19/17,884504882,200000000,863416141
2135,Pirates of the Caribbean: On Stranger Tides,Pirates of the Caribbean: On Stranger Tides,"[Adventure, Action, Fantasy]",Pirates of the Caribbean Collection,"[Walt Disney Pictures, Jerry Bruckheimer Films...",http://disney.go.com/pirates/index-on-stranger...,en,136.0,2011,5/14/11,1167365622,380000000,1045713802
2209,Pirates of the Caribbean: At World's End,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",Pirates of the Caribbean Collection,"[Walt Disney Pictures, Jerry Bruckheimer Films...",http://disney.go.com/disneypictures/pirates/,en,169.0,2007,5/19/07,1163844406,300000000,961000000
2284,ゲド戦記,Tales from Earthsea,"[Adventure, Fantasy, Animation, Science Fiction]",NaN,"[Walt Disney Pictures, Studio Ghibli, Hakuhodo...",http://disney.go.com/disneypictures/earthsea/#...,ja,115.0,2006,7/29/06,84698789,22000000,68000000
2324,The Three Musketeers,The Three Musketeers,"[Adventure, Action, Thriller]",NaN,"[Impact Pictures, Studio Babelsberg, Nouvelles...",http://www.threemusketeers-movie.com/,en,110.0,2011,8/31/11,147662472,75000000,132274484
2429,Tuck Everlasting,Tuck Everlasting,"[Drama, Family, Fantasy, Romance, Science Fict...",NaN,[Walt Disney Pictures],NaN,en,90.0,2002,10/11/02,26741114,15000000,19158074
2442,Race to Witch Mountain,Race to Witch Mountain,"[Adventure, Family, Fantasy, Science Fiction, ...",NaN,"[Walt Disney Pictures, Gunn Films]",NaN,en,98.0,2009,3/12/09,124424577,50000000,106303988
2472,The Good Dinosaur,The Good Dinosaur,"[Adventure, Animation, Family]",NaN,"[Walt Disney Pictures, Pixar Animation Studios]",http://movies.disney.com/the-good-dinosaur,en,93.0,2015,11/14/15,351658231,175000000,331926147
2562,Finding Dory,Finding Dory,"[Adventure, Animation, Comedy, Family]",Finding Nemo Collection,"[Walt Disney Pictures, Pixar Animation Studios...",http://movies.disney.com/finding-dory,en,97.0,2016,6/16/16,1076140905,200000000,1028570889
2629,Homeward Bound II: Lost in San Francisco,Homeward Bound II: Lost in San Francisco,"[Adventure, Comedy, Drama, Family]",Homeward Bound Collection,[Walt Disney Pictures],NaN,en,89.0,1996,3/8/96,52349044,0,32709423
2669,Pocahontas,Pocahontas,"[Adventure, Animation, Drama, Family]",Pocahontas Collection,"[Walt Disney Pictures, Walt Disney Feature Ani...",NaN,en,81.0,1995,6/14/95,570230010,55000000,346079773
2707,Max Keeble's Big Move,Max Keeble's Big Move,"[Comedy, Family, Fantasy, Science Fiction]",NaN,"[Walt Disney Pictures, Karz Entertainment]",NaN,en,86.0,2001,10/5/01,24518565,12000000,17292381
2738,Atlantis: The Lost Empire,Atlantis: The Lost Empire,"[Animation, Family, Adventure, Science Fiction]",Atlantis Collection,"[Walt Disney Pictures, Walt Disney Feature Ani...",http://www.disney.com/atlantis,en,95.0,2001,6/2/01,263802330,120000000,186053725
2739,The Incredibles,The Incredibles,"[Action, Adventure, Animation, Family]",The Incredibles Collection,"[Walt Disney Pictures, Pixar Animation Studios]",http://disney.go.com/disneyvideos/animatedfilm...,en,115.0,2004,11/5/04,839383427,92000000,631442092
2771,Flight of the Navigator,Flight of the Navigator,"[Family, Science Fiction, Adventure]",NaN,"[Walt Disney Pictures, New Star Entertainment,...",NaN,en,90.0,1986,7/30/86,42533798,0,18564613
2806,Sky High,Sky High,"[Adventure, Comedy, Family]",NaN,"[Walt Disney Pictures, Gunn Films, Max Strongh...",http://disney.go.com/disneypictures/skyhigh/,en,100.0,2005,7/29/05,111050000,35000000,86369815
2858,Cars,Cars,"[Animation, Adventure, Comedy, Family]",Cars Collection,"[Walt Disney Pictures, Pixar Animation Studios]",http://disney.go.com/disneyvideos/animatedfilm...,en,117.0,2006,6/8/06,575432552,120000000,461983149
2866,National Treasure: Book of Secrets,National Treasure: Book of Secrets,"[Action, Adventure, Mystery, Thriller]",National Treasure Collection,"[Walt Disney Pictures, Jerry Bruckheimer Films...",http://disney.go.com/disneypictures/nationaltr...,en,124.0,2007,12/13/07,553901732,130000000,457363168
2899,Dinosaur,Dinosaur,"[Animation, Family]",NaN,"[Walt Disney Pictures, Walt Disney Feature Ani...",NaN,en,82.0,2000,5/19/00,516574729,127500000,354248063
2943,James and the Giant Peach,James and the Giant Peach,"[Adventure, Animation, Family]",NaN,"[Walt Disney Pictures, Allied Filmmakers]",http://movies.disney.com/james-and-the-giant-p...,en,79.0,1996,4/12/96,46286372,38000000,28921264

In [9]:
disney_sequel_df = disney_df[disney_df['collection'] != 'NaN']
disney_sequel_df.head()

,original_title,title,genre,collection,production_company,homepage,original_language,runtime,release_year,release_date,adjusted_revenue,budget,revenue
1,The Princess Diaries 2: Royal Engagement,The Princess Diaries 2: Royal Engagement,"[Comedy, Drama, Family, Romance]",The Princess Diaries Collection,[Walt Disney Pictures],NaN,en,113.0,2004,8/6/04,126483267,40000000,95149435
8,Muppet Treasure Island,Muppet Treasure Island,"[Action, Comedy, Music, Family, Adventure]",The Muppet Collection,"[Walt Disney Pictures, Jim Henson Productions,...",NaN,en,100.0,1996,2/16/96,54938484,0,34327391
121,Tarzan,Tarzan,"[Adventure, Animation, Drama, Family]",Tarzan (Animation) Collection,[Walt Disney Pictures],http://disneydvd.disney.go.com/tarzanr-special...,en,88.0,1999,6/18/99,675245714,150000000,448000000
155,Return to Never Land,Return to Never Land,"[Adventure, Fantasy, Animation, Family]",Peter Pan Collection,"[Walt Disney Pictures, Walt Disney Television ...",NaN,en,72.0,2002,2/14/02,153347907,20000000,109862682
314,Cars 3,Cars 3,"[Family, Comedy, Animation, Adventure]",Cars Collection,"[Walt Disney Pictures, Pixar Animation Studios]",http://cars.disney.com,en,109.0,2017,6/15/17,358722880,175000000,350170057

In [10]:
def movie_with_sequels(sequel_df):

    # find movie names with collections 
    collection_names = sequel_df[sequel_df.duplicated(subset = 'collection', keep = 'first')]['collection']
    # movie collection df 
    movie_wcollection = sequel_df[sequel_df['collection'].isin(collection_names)]
    
    # find movie names with collections 
    collection_names = sequel_df[sequel_df.duplicated(subset = 'collection', keep = 'first')]['collection']
    # movie collection df 
    movie_wcollection = sequel_df[sequel_df['collection'].isin(collection_names)]

    # find the total number of movies in the movie collection
    num_movies = movie_wcollection.groupby(['collection']).count().reset_index()[['collection', 'title']].rename(columns = {'title': 'num_movies'})

    # add the finding above to the movie collectin df
    movie_wcollection = pd.merge(num_movies, movie_wcollection, on = 'collection', how = 'left')

    collection_df = movie_wcollection.groupby(['collection', 'original_title']).agg({'release_year': 'sum',
                                                                                    'num_movies': 'sum',
                                                                                    'runtime': 'sum',
                                                                                    'budget': 'sum',
                                                                                    'adjusted_revenue': 'sum'})

    return collection_df

In [11]:
disney_sequel_df = movie_with_sequels(disney_sequel_df)
# disney_sequel_df

In [12]:

savanna = ['Dinosaur', 'The Lion King']
castle =  ['Alice in Wonderland', 'Beauty and the Beast']
water =  ['Finding Dory', 'Pirates of the Caribbean: The Curse of the Black Pearl']
jungle = ['Tarzan', 'The Jungle Book 2']

location_list = [savanna, castle, water, jungle]

In [13]:
location_revenue_df = []

for i in range(len(location_list)):
    location_df = pd.DataFrame({})
    
    for j in range(len(location_list[i])):
        
        movie_name = location_list[i][j] 
        one_df = disney_df[disney_df['original_title'] == movie_name]
        location_df = pd.concat([location_df, one_df])
    
    location_revenue_df.append(location_df)

In [14]:

data = []

trace = go.Bar(x = ['savanna', 'castle', 'water', 'jungle'],
               y = [location_revenue_df[i]['adjusted_revenue'].sum() for i in range(len(location_revenue_df))])
data.append(trace)
# work on: color of the bars, i.e. blue for water, green for jungle...   

layout = dict(title = 'major sceneries and their revenues',
              xaxis = dict(title = 'major sceneries'),
              yaxis = dict(title = 'revenue (adjusted to the value in 2018)'),
              width = 1000,
              height = 600,
              margin = dict(l = 10, r = 10, b = 200, t = 100, pad = 4))

fig = dict(data = data, layout = layout)

plotly.offline.iplot(fig)

### Sequels

In [15]:
sequel_df = df[df['collection'] != 'NaN']
sequel_df.head()

,original_title,title,genre,collection,production_company,homepage,original_language,runtime,release_year,release_date,adjusted_revenue,budget,revenue
0,Hot Tub Time Machine 2,Hot Tub Time Machine 2,[Comedy],Hot Tub Time Machine Collection,"[Paramount Pictures, United Artists, Metro-Gol...",NaN,en,93.0,2015,2/20/15,13046722,14000000,12314651
1,The Princess Diaries 2: Royal Engagement,The Princess Diaries 2: Royal Engagement,"[Comedy, Drama, Family, Romance]",The Princess Diaries Collection,[Walt Disney Pictures],NaN,en,113.0,2004,8/6/04,126483267,40000000,95149435
8,Muppet Treasure Island,Muppet Treasure Island,"[Action, Comedy, Music, Family, Adventure]",The Muppet Collection,"[Walt Disney Pictures, Jim Henson Productions,...",NaN,en,100.0,1996,2/16/96,54938484,0,34327391
10,Rocky,Rocky,[Drama],Rocky Collection,[United Artists],NaN,en,119.0,1976,11/21/76,517373744,1000000,117235147
11,Revenge of the Nerds II: Nerds in Paradise,Revenge of the Nerds II: Nerds in Paradise,[Comedy],Revenge of the Nerds Collection,"[Twentieth Century Fox Film Corporation, Amerc...",NaN,en,98.0,1987,7/10/87,50049057,0,22642033

In [16]:
collection_df = movie_with_sequels(sequel_df)
# collection_df

In [17]:
collection_to_plot = ['Alien Collection', 'Resident Evil Collection', 'Transformers Collection', 'The Fast and the Furious Collection', 'Ice Age Collection']

list_of_df = []

for i in range(len(collection_to_plot)):
    
    one_collection_df = collection_df[collection_df['num_movies'] == 4].loc[collection_to_plot[i]].reset_index()
    one_collection_df = one_collection_df.sort_values('release_year')
    
    list_of_df.append(one_collection_df)

In [21]:

data = []

for i in range(len(list_of_df)):
    trace = go.Scatter( x = list_of_df[i]['original_title'],
                        y = list_of_df[i]['adjusted_revenue'],
                        name = collection_to_plot[i],                   
                        mode = 'lines+markers')
    data.append(trace)
    

layout = dict(title = 'movie sequels and their revenues',
              xaxis = dict(title = 'movie name'),
              yaxis = dict(title = 'revenue (adjusted to the value in 2018)'),
              width = 1000,
              height = 600,
              margin = dict(l = 50, r = 10, b = 200, t = 100, pad = 4))

fig = dict(data = data, layout = layout)

plotly.offline.iplot(fig)
plotly.offline.plot(fig, filename = 'movie_sequels_and_revenues')

/Users/yueying.teng/miniconda3/lib/python3.6/site-packages/plotly/offline/offline.py:459: UserWarning:

Your filename `movie_sequels_and_revenues` didn't end with .html. Adding .html to the end of your file.

'file:///Users/yueying.teng/Documents/TMDB/movie_sequels_and_revenues.html'